### ISSUE TITLE
Dataset model updates

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-workbench#485]
We need to update dataset model in order to be fully compatible with doi. In fact we could copy most fields from doi into dataset. Dataset will then better serve as 'dynamic' DOI for analytical datasets (while DOI may represent different other kinds of data and documents that are not comparable to analytical dataset composed of samples, analysis, results with related tables).

**Comment by ollehints** [comment]
mostly done, models and config updated, permissions need te be created for dataset_geolocation

**Comment by enmust** [comment]
Closing this as a new issue was created for perms, see #653
