### ISSUE TITLE
rotate images script

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-workbench#638]
It should be possible to rotate images (photo archive and drillcore images) in server. currently it is only possible to correct the problem by deleting and uploading new version. It should only work for images that the current user has access to. 
The function should rotate both the main image and previews by 90 deg clockwise in one step. 
NB! the images should be rotated without recalculating pixel colors to avoid loss in quality.

**Comment by ollehints** [comment]
for instance, here boxes 2-3 need 180 deg rotation: https://dev.geoloogia.info/drillcore/4/

**Comment by Erikdzo** [comment]
Endpoint `/rotate_image` added to RWAPI.

To rotate images, POST request can be done on that endpoint with parameters 'image_ids' (array) and 'degrees' (number). There is also a optional parameter 'folders' (array) to specify the folders in which the rotation should be done (valid array elements are: '', '/small', '/medium', '/large').

The request fails when user does not have access to an image in the array, an image in the array can not be found.

Example `/rotate_image` POST request:
```
{
'image_ids': [1, 2, 3],
'degrees': 90,
'folders': ['', '/small'] (optional)
}
```
