### ISSUE TITLE
Drillcore box view issues

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-workbench#639]
- Can save but not view core diameter field "d, m" 
- cannot save field "Storage"
- "Depth start" corresponds to "Strat. top", thus "strat. base" should be below "strat. top", and same with strat. base free and top free.
-  "Muud sügavbused" should be "Muud sügavused"
- Field location not needed (is replaced by storage_id) - cannot change it also
- cannot change/save field stratigraphy_free
- NB! saving the box record resulted in loosing links to core box images - this only become evident after reload - thus used did not notice that the linked imaged were lost. Files can be restored one by one but this is painful - files come very slowly in multiselect due to guardian permission check.
- box images show up with delay - due to guardian

(tested on https://edit2.geocollections.info/drillcore_box/5587 and other from the same core)

**Comment by ollehints** [comment]
Loss of related data (links to box images) seems to occur when saving the data before the existing images have arrived.

**Comment by enmust** [comment]
Can be closed after #640 for files is resolved

**Comment by enmust** [comment]
Should be ok now
