### ISSUE TITLE
link locality to area

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-workbench#706]
It should be possible to assign locality to area. This relation would allow retrieving information for e.g., mineral deposits.
Add field area to locality form before mindat field.

**Comment by ollehints** [comment]
database updated with area_id field

**Comment by enmust** [comment]
Problem with migrations, can't add field to locality table as it throws a weird error saying 'invalid default value for "date_added"'

**Comment by enmust** [comment]
Duplicate of #763
