### ISSUE TITLE
Stratotypes hidden in stratigraphy view

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-workbench#728]
Stratotypes in subform are hidden in stratigraphy view and cannot be edited, for instance, https://edit2.geocollections.info/stratigraphy/435 should have two rows, https://stratigraafia.info/term/435

**Comment by Erikdzo** [comment]
Something weird seems to be going on.

The query made by workbench returns zero stratotypes for stratigraphy 435 (https://rwapi.geocollections.info/stratigraphy_stratotype/?stratigraphy=435&page=1&paginate_by=10&format=json),
 but other stratigraphy show stratotypes just fine, for example (https://edit2.geocollections.info/stratigraphy/23).

Furthermore, just quering for all stratotypes, shows no stratotype with stratigraphy 435 (https://rwapi.geocollections.info/stratigraphy_stratotype/?order_by=stratigraphy).

But adding `fields` parameter makes the stratotypes suddenly show up (https://rwapi.geocollections.info/stratigraphy_stratotype/?fields=id,stratigraphy&order_by=stratigraphy)

Also the count changes from 314 -> 374. So there is more stratotypes that are somehow hidden.

**Comment by ollehints** [comment]
solved by updating API config
