### ISSUE TITLE
Dataset issues

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-workbench#737]
- [ ] Dataset title and title_en fields should be used in autocompletes (not name and name_en), for instance, in analysis view.
- [x] It should be possible to add analysis to dataset manually (by selecting analysis id-s) in dataset detail view, analysis subform
- [x] Additionally (in future), it should be possible to add selection of multiple analyses to a dataset (note that one analysis may belong to multiple datasets - and additionally an analysis may belong to a primary dataset with direct relation)
- [x] #742

**Comment by Erikdzo** [comment]
There is no such field as `title_en` in dataset. Should this be added? What was the difference between `title` and `name`?
