### ISSUE TITLE
Sample attachment links disappear

### ISSUE THREAD

**Issue by Erikdzo** [geocollections/sarv-workbench#745]
**EDIT**: https://github.com/geocollections/sarv-workbench/issues/745#issuecomment-1297096788 describes the real problem

For some reason cannot add more than 10 attachments to a sample permanently. 

Users say that when initially adding the attachment link they are created but the next day only the last 10 remain.

Ex. https://edit2.geocollections.info/sample/67776 
There should be 12 attachments linked, currently there are 11 as of 28.10.2022. Before this issue was created there were 10, i added one back to see if they really disappear.

It might not be exactly true that more than 10 attachments are not allowed as, 93234 and 92440 have 16 and 11 respectively and existed more than a day. This may point to the fact that maybe these missing attachment links, where never in the database to begin with.

Could this in reality be related to uploading more than 10 files at a time from the FileInput component? The weird thing is that the attachments themselves have been created but the attachment links are missing.

**Comment by Erikdzo** [comment]
The real problem is pagination on the attachment tab.

If user adds more than 10 (or the pagination selected) attachments and then presses save, then the attachment link are overridden only the ones visible in the tab are saved. 

The current quick solution is to remove pagination component from the attachment tab and set the default pagination to 100. So that the users cannot accidentally delete  attachment links.

This solution is implemented on the Sample page. Need to also implement it on every other page where attachments can be added.

**Comment by enmust** [comment]
default pagination is set to 100 now. If there are too many attachments the current existing files component isn't the best.
