### ISSUE TITLE
stratigraphy view issues

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-workbench#782]
- [x] can add stratotypes, but later cannot see/edit them if type not indicated, https://geoloogia.info/stratigraphy/385/ vs https://edit2.geocollections.info/stratigraphy/385
- [x] should be possible to delete stratotypes
- [x] should be possible to delete related references
- [x] should be possible to delete synonyms
- [x] from reference view, it should be possible to add new relation to stratigraphy but not a new stratigraphy records

**Comment by Erikdzo** [comment]
> can add stratotypes, but later cannot see/edit them if type not indicated, https://geoloogia.info/stratigraphy/385/ vs https://edit2.geocollections.info/stratigraphy/385

A mismatch between Django models and database schema caused the api to think that the stratotype field is not nullable and therefore can be joined using `INNER JOIN`. Making the fields nullable in the model fixed the issue. (https://github.com/geocollections/rwapi/commit/2c556d4ddd9f36ddf723245e17337b2b73b7a448#diff-94bcb48076bc0c4d012f00695239dbe7442de6fa44a5a4a2de03a630fc4659a7)
